Metrics/MethodLength:
  Max: 11

Style/Lambda:
  EnforcedStyle: literal

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/*'
    - 'db/**/*'

Metrics/LineLength:
  Max: 85
  Exclude:
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/puma.rb'
    - 'db/**/*'

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
    - 'db/**/*'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*'
    - 'db/**/*'
