# PG version 1.2.2
#   gem install pg
#
#   Ensure the Postgresql gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  timeout: <%= ENV['DB_TIMEOUT'] || 5000 %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || rubytify_dev %>
  localhost: <%= ENV['DB_LOCALHOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'rubytify_test' %>

production:
  <<: *default
  database: <%= ENV['DB_URL'] %>
