default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubytify_development

test:
  <<: *default
  database: rubytify_test

production:
  <<: *default
  database: rubytify_production
  username: rubytify
  password: <%= ENV['RUBYTIFY_DATABASE_PASSWORD'] %>
