default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1zM26R15
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: 127.0.0.1
test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>
production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>