defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  password:

development:
  <<: *defaults
  database: rubytify_development

test:
  <<: *defaults
  database: rubytify_test

production:
  <<: *defaults
  database: rubytify_production