development:
  adapter: postgresql
  username: xetkdvkzduuhrw
  password: cc116fddec843c8e86acdc9e1c2168fb3c809f16bbd2b33e80b26631d8d5aa7e
  port: 5432
  encoding: utf8
  host: ec2-174-129-254-238.compute-1.amazonaws.com

test:
  adapter: postgresql
  username: xetkdvkzduuhrw
  password: cc116fddec843c8e86acdc9e1c2168fb3c809f16bbd2b33e80b26631d8d5aa7e
  port: 5432
  encoding: utf8
  host: ec2-174-129-254-238.compute-1.amazonaws.com

production:
  adapter: postgresql
  username: xetkdvkzduuhrw
  password: cc116fddec843c8e86acdc9e1c2168fb3c809f16bbd2b33e80b26631d8d5aa7e
  port: 5432
  encoding: utf8
  host: ec2-174-129-254-238.compute-1.amazonaws.com