development: &default
  adapter: postgresql
  encoding: unicode
  database: ruby_tify_db
  username: <%= ENV['USERNAME_DB'] %>
  password: <%= ENV['PASSWORD_DB'] %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>

test: &test
  <<: *default
  adapter: postgresql
  database: ruby_tify_db_test

production:
  adapter: postgresql
  encoding: unicode
  database: ruby_tify_db_production
