# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#


development:
  adapter: postgresql
  database: rubytify_development
  pool: 5
  timeout: 5000
  host: localhost
  user: postgres
  password: postgres


test:
  adapter: postgresql
  database: rubytify_test
  pool: 5
  timeout: 5000
  host: localhost
  user: postgres
  password: postgres


production:
  adapter: postgresql
  database: rubytify_production
  pool: 5
  timeout: 5000
  host: localhost
  user: postgres
  password: postgres
  #password: <%= ENV['RUBYTIFY_DATABASE_PASSWORD'] %>
